# Generated by Django 3.1.1 on 2021-09-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf', '0008_auto_20210912_2345'),
        ('vendor', '0002_auto_20210912_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REQUESTED', 'REQUESTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED_BY_USER', 'CANCELLED_BY_USER'), ('CANCELLED_BY_VENDOR', 'CANCELLED_BY_VENDOR')], default='REQUESTED', max_length=100)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT_CARD', 'CREDIT_CARD'), ('PAYPAL', 'PAYPAL'), ('OTHER', 'OTHER'), ('NOT_SPECIFIED', 'NOT_SPECIFIED'), ('UPI', 'UPI'), ('DEBIT_CARD', 'DEBIT_CARD')], default='NOT_SPECIFIED', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
