# Generated by Django 3.1.1 on 2021-09-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
    ]
