# Generated by Django 3.1.1 on 2021-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210919_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('APPROVED_BY_VENDOR', 'APPROVED_BY_VENDOR'), ('REQUESTED', 'REQUESTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED_BY_USER', 'CANCELLED_BY_USER'), ('CANCELLED_BY_VENDOR', 'CANCELLED_BY_VENDOR')], default='REQUESTED', max_length=100),
        ),
    ]
