# Generated by Django 3.1.1 on 2021-06-20 05:31

import api.turf.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ground',
                'verbose_name_plural': 'grounds',
            },
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=2000)),
                ('rules', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=5000)),
                ('amenities', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'turf',
                'verbose_name_plural': 'turfs',
            },
        ),
        migrations.CreateModel(
            name='TurfPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=api.turf.models.path_and_rename)),
                ('turfId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf')),
            ],
            options={
                'verbose_name': 'ground',
                'verbose_name_plural': 'grounds',
            },
        ),
    ]
