# Generated by Django 3.1.1 on 2021-06-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='vendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='ground',
            name='turfId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf'),
        ),
        migrations.AlterUniqueTogether(
            name='turf',
            unique_together={('name', 'slug')},
        ),
    ]
