# Generated by Django 3.1.1 on 2021-06-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_auto_20210620_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='turf_ground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turf_ground', to='turf.ground'),
        ),
    ]
