# Generated by Django 3.1.1 on 2021-06-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_turf_turf_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='turf_ground',
        ),
        migrations.AddField(
            model_name='turf',
            name='turf_ground',
            field=models.ManyToManyField(null=True, related_name='turf_ground', to='turf.Ground'),
        ),
    ]
