# Generated by Django 3.1.1 on 2021-08-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_remove_turf_turf_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='turfId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_ground', to='turf.turf'),
        ),
    ]
