# Generated by Django 3.1.1 on 2021-08-03 15:37

import api.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.user.models.UserManager()),
            ],
        ),
    ]
